#!/usr/bin/env python
import os
import sys

UTF8_BOM = b'\xEF\xBB\xBF'

if __name__ == '__main__':
    filename = sys.argv[1]

    success = False

    tmp_filename = f'{filename}.remove_bom.tmp'
    with open(filename, 'rb') as infile, open(tmp_filename, 'wb') as outfile:
        maybe_bom = infile.read(3)
        if maybe_bom == UTF8_BOM:
            outfile.write(infile.read())
            success = True
        else:
            sys.stderr.write('No UTF-8 BOM detected.\n')
            success = False

    if success:
        os.replace(tmp_filename, filename)
    else:
        os.remove(tmp_filename)
        sys.exit(1)
